# See LICENSE file for full copyright and licensing details.

{
    "name": "Cash Collection",
    "version": "12.0.1.0.0",
    "author": "Enzapps",
    "category": "Accounting",
    "website": "http://www.enzapps.com/",
    "depends": ["sale", "purchase", "account", "ezp_estimate", "opening_balance_customers", "web_notify",
                "salesperson_target"],
    "license": "",
    "summary": "Cash Collection",
    "data": [
        "security/cah_security.xml",
        "security/ir.model.access.csv",
        "data/cash_collection.xml",
        "data/schedule.xml",
        "views/accountant_record.xml",
        "views/assets.xml",
        "views/cash_collection.xml",
        "views/executive_collection.xml",
        "views/purchase_collection.xml",
        "views/data_collection.xml",
        "views/cheque_flow.xml",
        "views/cheque_repo.xml",
        "views/orders_custom.xml",
        "views/supplier_ledger.xml",
        "views/today_cheque_collection.xml",
        "views/amount_withdraw.xml",
        "views/cheque_submission.xml",
        "views/rtgs_collection.xml",
        "views/datewise_collection.xml",
        "views/executive_cheque_collection.xml",
        "views/expenses_collection.xml",
        "views/customer_aged_repo.xml",
        "views/freight_disc.xml",
        "views/owner_application.xml",
        "views/executive_area_assign.xml",
        "views/estimate_type.xml",
        "views/cash_direct_collection.xml",
        "report/collection.xml",
        "report/ledger.xml",
        "report/collection_executive.xml",
        "report/collection_cashier.xml",
        "report/pay_cashier.xml",
        "report/test.xml",
        "report/expenses_report.xml",
        "report/collection_data.xml",
        "report/eay.xml",
        "report/direct_collection_cashier.xml",
        "report/collection_cheque_executive.xml",
        "report/daybook_summary_view.xml",
        "report/collection_cheque_casheir.xml",
        "report/report_est_type_view.xml",
        "report/einv_invoice_report.xml",
        "wizard/daybook_reporting.xml",
        "wizard/daybook_reporting.xml",
        "views/configuration.xml",
        "views/credit.xml",

    ],
    # "css": ["static/src/css/room_kanban.css"],
    "images": ["static/description/Hotel.png"],
    "qweb": ["static/src/xml/building_room_summary.xml"],
    "application": True,
}
